language: c

sudo: false

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=luajit
    - LUA=luajit2.0
    - LUA=luajit2.1

before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks install busted

script:
  - busted --verbose

branches:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: always
