language: c

sudo: false

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=luajit
    - LUA=luajit2.0
    - LUA=luajit2.1

before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks install busted
  - luarocks install luacov
  - luarocks install cluacov

script:
  - busted --verbose

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 36624b2d-d94d-487f-a793-7ae95b2e521a

branches:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: always
